[build]
  base = "frontend"
  command = "npm run build:prod"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_CACHE = "/opt/buildhome/.npm"

[[redirects]]
  from = "/api/*"
  to = "https://frostsnow35-blog.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
